# Generated by Django 4.2.6 on 2023-12-02 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_managers_comment_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
